collect_tweets/urls.py
from django.urls import path

from . import views
app_name = 'collect_tweets'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/<str:handle>', views.search, name='search'),
    path('monitor', views.monitor_handle, name='monitor'),
    path('register',views.register,name="register"),
    path('delete',views.delete,name="delete"),
    path('delete_account',views.delete_account,name="delete_account")
]

twitter_app/urls.py
from django.contrib import admin
from django.urls import include, path
urlpatterns = [
    path('admin/', admin.site.urls),
    path('collect_tweets/', include('collect_tweets.urls')),
]

collect_tweets/models.py
from django.db import models


class Account(models.Model):
    handle = models.CharField(max_length=200,primary_key=True)
    count = models.IntegerField(default=0)
    id = models.IntegerField(default=0)
    def __str__(self):
        return self.handle
    def isActiveUser(self):
        return self.count > 100

collect_tweets/views.py
# Create your views here.
from django.http import HttpResponse, response
from django.shortcuts import get_object_or_404, render

from .models import Account
from twitter_app import settings
import requests


def index(request):
    popular_account = Account.objects.order_by('count')[:5]
    context = {
        'popular_account': popular_account
    }
    return render(request, 'collect_tweets/index.html', context)


def search(request, handle):
    search_result = get_object_or_404(Account, pk=handle)
    return render(request, 'collect_tweets/search.html', {'search': search_result})


def monitor_handle(request):
    return render(request, 'collect_tweets/monitor.html')


def delete(request):
    return render(request, 'collect_tweets/delete.html')


def delete_account(request):
    handle = request.POST['handle']
    account = Account.objects.get(pk=handle)
    if account:
        account.delete()
    return render(request, 'collect_tweets/delete_success.html', {'handle': handle})


def register(request):
    handle = request.POST['handle']
    url = f"https://api.twitter.com/2/users/by/username/{handle[1:]}?expansions=pinned_tweet_id&user.fields=created_at&tweet.fields=public_metrics"
    response = requests.request("GET",url, headers={
        "Authorization": f"Bearer {settings.TWITTER_BEARER_TOKEN}"
    })
    response = response.json()
    data = response['data']
    id = data.get('id',0)
    count = 0
    try:
        public_metrics = response['includes']['tweets'][0].get('public_metrics',{})
        if public_metrics:
            for metric in public_metrics:
                count += public_metrics[metric]
    except:
        pass
    account = Account()
    account.handle = handle
    account.id = id
    account.count = count
    account.save()
    return render(request, 'collect_tweets/register.html', {'account': account})

collect_tweets/templates/collect_tweets/delete.html
<form action="{% url 'collect_tweets:delete_account'%}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>Delete Account</h1></legend>
        <label>Twitter Handle: </label>
        <input type="text" name="handle">
    </fieldset>
    <input type="submit">
</form>
<a href="{% url 'collect_tweets:index' %}">Home</a>

collect_tweets/templates/collect_tweets/delete_success.html
{% if handle %}
<h1>Successfully deleted Handle {{handle}}</h1>
{% else %}
    <p>Account not found.</p>
{% endif %}
<a href="{% url 'collect_tweets:index' %}">Home</a>

collect_tweets/templates/collect_tweets/index.html
<h1>Twiiter Analytic</h1>
<a href="{% url 'collect_tweets:monitor'%}">Monitor</a>
<a href="{% url 'collect_tweets:delete'%}">Delete</a>
<br/>
<br/>
<label>All account:</label>
{% if popular_account %}
    <ul>
    {% for account in popular_account %}
        <li><a href="{% url 'collect_tweets:search' account.handle %}">{{ account.handle }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No handles are available.</p>
{% endif %}

collect_tweets/templates/collect_tweets/monitor.html
<form action="{% url 'collect_tweets:register'%}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>Monitor Account</h1></legend>
        <label>Twitter Handle: </label>
        <input type="text" name="handle">
    </fieldset>
    <input type="submit">
</form>
<a href="{% url 'collect_tweets:index' %}">Home</a>

collect_tweets/templates/collect_tweets/register.html
<h1>Successfully Registered Handle {{account.handle}}</h1>
<h1>ID: {{account.id}}</h1>
<h1>Tweets count: {{account.count}}</h1>
<a href="{% url 'collect_tweets:search' account.handle  %}">{{ account.handle }}</a>
<a href="{% url 'collect_tweets:index' %}">Home</a>

collect_tweets/templates/collect_tweets/search.html
<h1>{{ search.handle }}</h1>
<h2> User id: {{search.id}}</h2>
<h2> Tweets counts: {{search.count}}</h2>
<a href="{% url 'collect_tweets:index' %}">Home</a>